accounts/urls.py
from django.urls import path

from .views import SignUpView, email_update, users


urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("email_update", email_update, name="email_update"),
    path("users", users, name="users"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

polls/urls.py
from django.urls import path

from . import views

app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from django.db import connection #remove flaw-4
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from .forms import SignUpForm


class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

@login_required
def email_update(request):
    if request.method == "GET":
        return render(request, "email_update.html")
    if request.method == "POST":
        username = request.user
        email = request.POST.get('email')
        # FLAW-4
        # Injection through email update
        sql = f"UPDATE auth_user SET email='{email}' WHERE username='{username}'" #remove flaw-4
        with connection.cursor() as cursor: #remove flaw-4
            cursor.execute(sql) # remove flaw-4
        # FIX for flaw-4, injection through email update:
        # use Django's modules instead to prevent injection
        # user = User.objects.get(username=username)
        # user.email = email
        # user.save()
        return redirect("home")

@login_required
def users(request):
    # FLAW-5, broken access control
    # This page is meant to be accessed only by admins, not regular users
    # Remove lines to fix flaw-5
    users = User.objects.all().values('username', 'email') #remove flaw-5
    return render(request, "users.html", {"users": users}) #remove flaw5
    # End of REMOVE-block

    # FIX for flaw-5:
    # if request.user.is_staff and request.user.is_superuser:
    #    users = User.objects.all().values('username', 'email')
    #    return render(request, "users.html", {"users": users})
    # else:
    #    return HttpResponseForbidden("You are not authorized to see this content.")
    # End of FIX-block

polls/views.py
from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        raise Exception("You didn't select a choice") #remove flaw-1a
        # FLAW-1a
        # Poor exception handling combined with DEBUG = True in settings.py causes
        # the printing of environmental variables to browswer. This action is
        # triggered when the user clicks the 'Vote' button before having selected
        # an option to vote for. See also comments in mysite/settings.py.
        # Raising errors and exeptions can be used during development phase for
        # catching the errors and examining the values of local variables. However,
        # this kind of exception handling should not be in production.
        # FIX for flaw-1a: Better handling of exception, as provided in the code template:
        #return render(
        #    request,
        #    "polls/detail.html",
        #    {
        #        "question": question,
        #        "error_message": "You didn't select a choice",
        #    },
        #)
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block title %}Poll details{% endblock %}

{% block content %}
    {% include "login_info.html" %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
    </form>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block title %}Polls{% endblock %}

{% block content %}
    {% include "login_info.html" %}
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block title %}Poll results{% endblock %}

{% block content %}
    {% include "login_info.html" %}
    <h1>{{ question.question_text }}</h1>

    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
    <a href="{% url 'polls:index' %}">Back to polls</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
</head>

<body>
  {% load current_time %}
  Current time: {% time_now %}
  {% if user.is_authenticated %}
    <p>Username: {{ user.username }}, Email: {{ user.email }}</p>
    <p>Requirements for admin access:</p>
    <p>Is superuser: {{ user.is_superuser }}, Is staff: {{ user.is_staff }}</p>
  {% endif %}
  <main>
    {% block content %}
    {% endblock %}
  </main>
<footer>
  <a href="{% url 'home' %}">Back to home page</a>
</footer>
</body>

</html>

templates/email_update.html
{% extends "base.html" %}

{% block title %}Email Update{% endblock %}

{% block content %}
<h3>Update your password</h3>

<form method="post">
  {% csrf_token %}
  <label for email>New email address:</label>
  <input type="text" name="email" size="80"><br>
  <!--FIX for flaw 5, injection through email update:
  Use type="email" for input field:
  <input type="email" name="email"><br>
  Notice: This setting can be bypassed by the user
  by editing the code on browser!
  -->
  <input type="submit" value="Submit">
</form>

{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
  <p><a href="{% url 'polls:index' %}">Go to polls</a></p>
  {% if user.is_authenticated %}
    <p>Hi {{ user.username }}!</p>
    <p><a href="{% url 'password_change' %}">Password Change</a></p>
    <p><a href="{% url 'email_update' %}">Update Email Address</a></p>
    <form action="{% url 'logout' %}" method="post">
      {% csrf_token %}
      <button type="submit">Log Out</button>
    </form>
  {% else %}
    <p>You are not logged in</p>
    <p><a href="{% url 'password_reset' %}">Password Reset</a></p>
    <p><a href="{% url 'login' %}">Log In</a></p>
    <p><a href="{% url 'signup' %}">Sign Up</a></p>
  {% endif %}
{% endblock %}

templates/login_info.html
{% if user.is_authenticated %}
  <p>User: {{ user.username }}</p>
  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">Log Out</button>
  </form>
{% else %}
  <p>You are not logged in</p>
  <p><a href="{% url 'login' %}">Log In</a></p>
{% endif %}

templates/users.html
{% extends "base.html" %}

{% block title %}Users{% endblock %}

{% block content %}
  <h3>Registered users:</h3>
  {% for user in users %}
    <li>{{user.username}} {{user.email}}</li>
  {% endfor %}
  <br>
{% endblock %}